name: docker-build-publish

# Trigger on all push events, new semantic version tags, and all PRs
on:
  push:
    branches:
      - "main"
      - "v*"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: "The checkout reference (ie tag, branch, sha)"
        required: true
        type: string

jobs:
  docker-security-build:
    permissions:
      contents: write
      packages: write
    uses: chatton/.github/.github/workflows/reusable_dockerfile_pipeline.yml@c66f3849905ca6dd1ddbe3e4bd3150a710d1a3ce
    with:
      dockerfile: docker/Dockerfile
      checkout_ref: ${{ github.event.inputs.ref }}
    secrets: inherit

  docker-multiplexer-build:
    permissions:
      contents: write
      packages: write
    uses: chatton/.github/.github/workflows/reusable_dockerfile_pipeline.yml@c66f3849905ca6dd1ddbe3e4bd3150a710d1a3ce
    with:
      dockerfile: docker/multiplexer.Dockerfile
      checkout_ref: ${{ github.event.inputs.ref }}
      packageName: celestia-app-multiplexer
      buildArgs: "TARGETOS=linux TARGETARCH=amd64"
    secrets: inherit

  docker-txsim-build:
    permissions:
      contents: write
      packages: write
    uses: chatton/.github/.github/workflows/reusable_dockerfile_pipeline.yml@c66f3849905ca6dd1ddbe3e4bd3150a710d1a3ce
    with:
      dockerfile: docker/txsim/Dockerfile
      packageName: txsim
      checkout_ref: ${{ github.event.inputs.ref }}
    secrets: inherit
